= Typescript Notes
:toc:

== Concepts

=== https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types[Index Types] and https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types[Mapped Types]

* index type query operator `keyof T`
* index access operator `T[K]`
* Mapped Type
+
```typescript
type Readonly<T> = {
  readonly [P in keyof T]: T[P];
};
```

==== Mapped Type for Enum keys

```typescript
/**
 * Generate a String Literal Type that represents all Enum keys as strings
 * https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time
 */
type SomeEnumKeys = keyof typeof SomeEnum;
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#conditional-types[Conditional Types (2.8)]

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions[Const Assertions (3.4)]
____
When we construct new literal expressions with const assertions, we can signal to the language that

* no literal types in that expression should be widened (e.g. no going from "hello" to string)
* object literals get readonly properties
* array literals become readonly tuples

```typescript
// Type '"hello"'
let x = "hello" as const;

// Type 'readonly [10, 20]'
let y = [10, 20] as const;

// Type '{ readonly text: "hello" }'
let z = { text: "hello" } as const;
```
____

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining[Optional Chaining and Nullish Coalescing (3.7)]

```typescript
// Property
const a = foo?.bar?.baz;

// Array
return arr?.[0];

// Function
log?.(`Request started at ${new Date().toISOString()}`);
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types[Variadic Tuple Types (4.0)]

```typescript
type Arr = readonly any[];

function concat<T extends Arr, U extends Arr>(arr1: T, arr2: U): [...T, ...U] {
  return [...arr1, ...arr2];
}
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types[Template Literal Types (4.1)] 

https://github.com/microsoft/TypeScript/pull/40336[Original PR]

Creating large permutations of string literals
```typescript
type VerticalAlignment = "top" | "middle" | "bottom";
type HorizontalAlignment = "left" | "center" | "right";
declare function setAlignment(value: `${VerticalAlignment}-${HorizontalAlignment}`): void;
```

Typing event names that follow a required pattern
```typescript
type PropEventSource<T> = {
    on(eventName: `${string & keyof T}Changed`, callback: () => void): void;
};
```

With **indexed access operator**
```typescript
type PropEventSource<T> = {
    on<K extends string & keyof T>
        (eventName: `${K}Changed`, callback: (newValue: T[K]) => void ): void;
};
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types[Key Remapping in Mapped Types (4.1)]

```typescript
type Getters<T> = {
    [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K]
};
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#recursive-conditional-types[Recursive Conditional Types (4.1)]

https://github.com/microsoft/TypeScript/pull/40002[Original PR]

```typescript
type ElementType<T> = T extends ReadonlyArray<infer U> ? ElementType<U> : T;

function deepFlatten<T extends readonly unknown[]>(x: T): ElementType<T>[] {
  throw "not implemented";
}
```

=== https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions[Discriminated Unions]

```typescript
interface Circle {
  kind: "circle";
  radius: number;
}

interface Square {
  kind: "square";
  sideLength: number;
}

type Shape = Circle | Square;

function getArea(shape: Shape) {
  // Or if/else if works
  switch (shape.kind) {
    case "circle":
      return Math.PI * shape.radius ** 2;
    case "square":
      return shape.sideLength ** 2;
  }
}
```

== Common Patterns

=== I want a `Record<A, B>` type, but where A is a mapped type from an existing object's keys
This is useful when you want a Record with a consistent value type, but where the keys are a generated string literal (instead of just `Record<string, B>`).

```typescript
const ObjTemplate = {
  key1: value1,
  key2: value2
} as const;

const Obj: { [key in keyof typeof ObjTemplate]: ValueType } = ObjTemplate;
```

=== I want a `Record` type, where the keys are restricted to the strings in an array
From https://stackoverflow.com/q/56967820[here] and https://stackoverflow.com/a/52174119[explanation here "The standard trick supported by the compiler to do this is to run the array through an identity function that infers an element type constrained by string"]

```typescript
const ids = ['hello', 'world'] as const;

type RecordWithArrayKeys = Record<typeof ids[number], string>;
```

=== Typed nested property path strings like `lodash.get` (Template Literal Types and Recursive Conditional Types)

From https://stackoverflow.com/a/65140399[here]

```typescript
type Path<T> = T extends Array<any>
  ? `${number}` | `${number}.${Path<T[number]>}`
  : T extends object
  ? {
      [P in keyof T]: (P & string) | `${P & string}.${Path<T[P]>}`
    }[keyof T]
  : never
```

See "Expressjs Routes with typed parameters" for another possible solution to this.

=== Expressjs Routes with typed parameters (Template Literal Types and Recursive Conditional Types)
From https://davidtimms.github.io/programming-languages/typescript/2020/11/20/exploring-template-literal-types-in-typescript-4.1.html[Exploring Template Literal Types in TypeScript 4.1]

```typescript
type PathParams<Path extends string> =
    Path extends `:${infer Param}/${infer Rest}` ? Param | PathParams<Rest> :
    Path extends `:${infer Param}` ? Param :
    Path extends `${infer _Prefix}:${infer Rest}` ? PathParams<`:${Rest}`> :
    never;
```

=== Converting Unions to Tuples
From https://github.com/microsoft/TypeScript/issues/13298#issuecomment-724542300[here]

```typescript
type UnionToTuple<T> = (
    (T extends any ? (t: T) => T : never) extends infer U
        ? (U extends any ? (u: U) => any : never) extends (v: infer V) => any
            ? V
            : never
        : never
) extends (_: any) => infer W
    ? [...UnionToTuple<Exclude<T, W>>, W]
    : [];
```

=== I wanted to filter undefined elements from an array, and the resulting array typed with only the remaining type

Filtering out undefined elements from an array of type `(T | undefined)[]` the returned array remains the original type (even though no undefined elements remain) due to Typescript limitations.
Use a https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates[Type Predicate] to resolve this:

```typescript
const arr1: (number | undefined)[] = []
const arr2 = arr1.filter((item): item is number => item !== undefined) // arr2 is type string[]
```
