= Typescript Project Starters
:toc:

== Base
```bash
npm init -y

# Eslint and Prettier
npm i --save-dev eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser
npm i --save-dev prettier
wget https://raw.githubusercontent.com/nickscript0/dev-workflows/master/dot_rc_files/.eslintrc.json
wget https://raw.githubusercontent.com/nickscript0/dev-workflows/master/dot_rc_files/.eslintignore
wget https://raw.githubusercontent.com/nickscript0/dev-workflows/master/dot_rc_files/.prettierrc.json

npm i --save typescript

# Add a .gitignore with at least "node_modules/"
```

== NodeJS Project
```bash
npm i --save ts-node
npm i --save-dev @types/node
```

* Ensure your tsconfig.json has `module: "CommonJS"`

== NextJS App
. Run `npx create-next-app`
. Then https://nextjs.org/docs/basic-features/typescript[convert it to Typescript]
+
____
To get started, create an empty tsconfig.json file in the root of your project

Then, run next (normally npm run dev or yarn dev) and Next.js will guide you through the installation of the required packages to finish the setup
____

== Chrome/Firefox Extension
=== Webpack5
*This is the current best way until the Parcel.js manifest v3 support PR is merged (see Parcel.js section below)*.

Install deps
```bash
npm install save-dev webpack webpack-cli ts-loader typescript
```

==== webpack.config.js
A sample webpack.config.js that assumes your entrypoint is src/main.ts and bundles everything to build/main.bundle.js
```javascript
const path = require('path');

module.exports = {
    entry: {
        main: './src/main.ts',
    },
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: '[name].bundle.js',
        publicPath: '/build/',
    },
    resolve: {
        // Add `.ts` and `.tsx` as a resolvable extension.
        extensions: ['.webpack.js', '.web.js', '.ts', '.tsx', '.js'],
    },
    module: {
        rules: [
            // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
            { test: /\.tsx?$/, loader: 'ts-loader' },
        ],
    },
    mode: 'production',
    // Comment in for source maps
    // mode: 'development',
    // devtool: 'source-map'
};
```

==== manifest.json
Sample Manifest V3 with a content_script
```json
{
    "name": "Name",
    "version": "0.3",
    "description": "Description",
    "content_scripts": [
        {
            "matches": ["https://example.com/*"],
            "js": ["build/main.bundle.js"]
        }
    ],
    "manifest_version": 3
}
```

==== tsconfig.json
module must be CommonJS

```json
{
    "compilerOptions": {
        "target": "ESNext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
        "module": "CommonJS" /* This can be 'ESNext' for extensions, but not for nodejs scripts */,
        "strict": true /* Enable all strict type-checking options. */,
        "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
        "skipLibCheck": true /* Skip type checking of declaration files. */,
        "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */,
        "lib": ["ESNext", "DOM"]
    }
}
```

=== Parcel.js
* Has support for Manifest v2 built-in https://parceljs.org/recipes/web-extension/
* But currently waiting on a maintainer to merge this PR for Manifest v3 support (last checked Apr2, 2022)
** https://github.com/parcel-bundler/parcel/issues/6079
** https://github.com/parcel-bundler/parcel/pull/7050

=== Vite.js
*I experimented with Vite 2.9.1 on Apr 2, 2022, it works but requires independently configuring tsc to watch so no thanks.*

* It seems to work fine aftering setting up a tsconfig.json, and package.json output from `npm create vite@latest`, then using the dist/main.es.js output of https://vitejs.dev/guide/build.html#library-mode[Library-mode] using the following vite.config.js and build command `tsc && vite build`
+
```javascript
// vite.config.js
const path = require('path');
const { defineConfig } = require('vite');

module.exports = defineConfig({
    build: {
        lib: {
            entry: path.resolve(__dirname, 'src/main.ts'),
            name: 'Extension',
            fileName: format => `extension.${format}.js`,
        },
    },
});

