= Typescript Notes
:toc:

== Concepts

=== https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types[Index Types] and https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types[Mapped Types]

* index type query operator `keyof T`
* index access operator `T[K]`
* Mapped Type
+
```typescript
type Readonly<T> = {
  readonly [P in keyof T]: T[P];
};
```

==== Mapped Type for Enum keys

```typescript
/**
 * Generate a String Literal Type that represents all Enum keys as strings
 * https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time
 */
type SomeEnumKeys = keyof typeof SomeEnum;
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#conditional-types[Conditional Types (2.8)]

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions[Const Assertions (3.4)]
____
When we construct new literal expressions with const assertions, we can signal to the language that

* no literal types in that expression should be widened (e.g. no going from "hello" to string)
* object literals get readonly properties
* array literals become readonly tuples

```typescript
// Type '"hello"'
let x = "hello" as const;

// Type 'readonly [10, 20]'
let y = [10, 20] as const;

// Type '{ readonly text: "hello" }'
let z = { text: "hello" } as const;
```
____

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining[Optional Chaining and Nullish Coalescing (3.7)]

```typescript
// Property
const a = foo?.bar?.baz;

// Array
return arr?.[0];

// Function
log?.(`Request started at ${new Date().toISOString()}`);
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types[Variadic Tuple Types (4.0)]

```typescript
type Arr = readonly any[];

function concat<T extends Arr, U extends Arr>(arr1: T, arr2: U): [...T, ...U] {
  return [...arr1, ...arr2];
}
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types[Template Literal Types (4.1)] 

https://github.com/microsoft/TypeScript/pull/40336[Original PR]

Creating large permutations of string literals
```typescript
type VerticalAlignment = "top" | "middle" | "bottom";
type HorizontalAlignment = "left" | "center" | "right";
declare function setAlignment(value: `${VerticalAlignment}-${HorizontalAlignment}`): void;
```

Typing event names that follow a required pattern
```typescript
type PropEventSource<T> = {
    on(eventName: `${string & keyof T}Changed`, callback: () => void): void;
};
```

With **indexed access operator**
```typescript
type PropEventSource<T> = {
    on<K extends string & keyof T>
        (eventName: `${K}Changed`, callback: (newValue: T[K]) => void ): void;
};
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#key-remapping-in-mapped-types[Key Remapping in Mapped Types (4.1)]

```typescript
type Getters<T> = {
    [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K]
};
```

=== https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#recursive-conditional-types[Recursive Conditional Types (4.1)]

https://github.com/microsoft/TypeScript/pull/40002[Original PR]

```typescript
type ElementType<T> = T extends ReadonlyArray<infer U> ? ElementType<U> : T;

function deepFlatten<T extends readonly unknown[]>(x: T): ElementType<T>[] {
  throw "not implemented";
}
```

=== https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions[Discriminated Unions]

== Common Patterns

=== I want a `Record<A, B>` type, but where A is a mapped type from an existing object's keys
This is useful when you want a Record with a consistent value type, but where the keys are a generated string literal (instead of just `Record<string, B>`).

```typescript
const ObjTemplate = {
  key1: value1,
  key2: value2
} as const;

const Obj: { [key in keyof typeof ObjTemplate]: ValueType } = ObjTemplate;
```

=== Typed nested property path strings like `lodash.get`

From https://stackoverflow.com/a/65140399[here]

```typescript
type Path<T> = T extends Array<any>
  ? `${number}` | `${number}.${Path<T[number]>}`
  : T extends object
  ? {
      [P in keyof T]: (P & string) | `${P & string}.${Path<T[P]>}`
    }[keyof T]
  : never
```

See "Expressjs Routes with typed parameters" for another possible solution to this.

=== Expressjs Routes with typed parameters (Template Literal Types)
This is another posAnother possible solution is using the pattern https://davidtimms.github.io/programming-languages/typescript/2020/11/20/exploring-template-literal-types-in-typescript-4.1.html[David Timms uses here in his expressjs routes example]

```typescript
type PathParams<Path extends string> =
    Path extends `:${infer Param}/${infer Rest}` ? Param | PathParams<Rest> :
    Path extends `:${infer Param}` ? Param :
    Path extends `${infer _Prefix}:${infer Rest}` ? PathParams<`:${Rest}`> :
    never;
```
